ci: improve PR workflow

diff --git a/.github/workflows/updpkgsums.yml b/.github/workflows/updpkgsums.yml
--- a/.github/workflows/updpkgsums.yml
+++ b/.github/workflows/updpkgsums.yml
@@ -5,6 +5,7 @@ on:
     types:
       - opened
       - synchronize
+      - reopened
     branches:
       - master
 
@@ -14,7 +15,10 @@ jobs:
     permissions:
       # In order to make sure that the git-auto-commit-action has the permissions to write to the repository
       # using the $GITHUB_TOKEN, we have to add the write permissions to it.
-      contents: write 
+      contents: write
+      pull-requests: write
+    env:
+      GH_TOKEN: ${{ github.token }}
     steps:
       - name: Checkout
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
@@ -38,7 +42,16 @@ jobs:
 
       - name: Commit
         if: ${{ env.pkgbuild != '' }}
+        id: commit
         uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
         with:
           file_pattern: '*/PKGBUILD */.SRCINFO'
           commit_message: 'chore: update sha256sums and .SRCINFO'
+
+      - name: Fail if checksums were updated
+        if: ${{ steps.commit.outputs.changes_detected == 'true' }}
+        run: |
+          gh pr comment ${{ github.event.pull_request.number }} \
+            --body "I've updated the checksums in this PR. Please **close and reopen** the PR to re-trigger CI workflows."
+          echo "::error::Checksums were out of date and have been updated. Please close and reopen this PR to re-trigger CI."
+          exit 1
